# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edu_access_mapper_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SchoolDistributionAnalyzerDialogBase(object):
    def setupUi(self, SchoolDistributionAnalyzerDialogBase):
        SchoolDistributionAnalyzerDialogBase.setObjectName("SchoolDistributionAnalyzerDialogBase")
        SchoolDistributionAnalyzerDialogBase.resize(400, 170)
        self.labelSchool = QtWidgets.QLabel(SchoolDistributionAnalyzerDialogBase)
        self.labelSchool.setGeometry(QtCore.QRect(10, 20, 200, 30))
        self.labelSchool.setObjectName("labelSchool")
        self.comboBoxSchool = QtWidgets.QComboBox(SchoolDistributionAnalyzerDialogBase)
        self.comboBoxSchool.setGeometry(QtCore.QRect(220, 20, 160, 30))
        self.comboBoxSchool.setObjectName("comboBoxSchool")
        self.labelCities = QtWidgets.QLabel(SchoolDistributionAnalyzerDialogBase)
        self.labelCities.setGeometry(QtCore.QRect(10, 70, 200, 30))
        self.labelCities.setObjectName("labelCities")
        self.comboBoxCities = QtWidgets.QComboBox(SchoolDistributionAnalyzerDialogBase)
        self.comboBoxCities.setGeometry(QtCore.QRect(220, 70, 160, 30))
        self.comboBoxCities.setObjectName("comboBoxCities")
        self.runButton = QtWidgets.QPushButton(SchoolDistributionAnalyzerDialogBase)
        self.runButton.setGeometry(QtCore.QRect(150, 120, 100, 30))
        self.runButton.setObjectName("runButton")

        self.retranslateUi(SchoolDistributionAnalyzerDialogBase)
        QtCore.QMetaObject.connectSlotsByName(SchoolDistributionAnalyzerDialogBase)

    def retranslateUi(self, SchoolDistributionAnalyzerDialogBase):
        _translate = QtCore.QCoreApplication.translate
        SchoolDistributionAnalyzerDialogBase.setWindowTitle(_translate("SchoolDistributionAnalyzerDialogBase", "EduAccess Mapper"))
        self.labelSchool.setText(_translate("SchoolDistributionAnalyzerDialogBase", "Select School Layer:"))
        self.labelCities.setText(_translate("SchoolDistributionAnalyzerDialogBase", "Select Cities Layer:"))
        self.runButton.setText(_translate("SchoolDistributionAnalyzerDialogBase", "Run Analysis"))
